config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root "home#index"

  resources :articles
  resource :user, only: %i[edit update destroy]
  resources :users, only: %i[index show]

  get "/pages/:page" => "pages#show", as: :page

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#internal_server_error', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can [:read, :create], Article
    can [:update, :destroy], Article, user: user
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :title, :body, presence: true
  validates :title, length: { minimum: 5 }
  validates :body, length: { minimum: 50 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :omniauthable,
         omniauth_providers: [:facebook, :google_oauth2, :github]

  has_one_attached :avatar
  has_many :articles, dependent: :destroy

  def name
    @name ||= self[:name].presence || email.split("@").first
  end

  def self.from_omniauth(auth)
    data = auth.info

    User.where(email: data['email']).first_or_create do |user|
      user.name = data['name']
      user.password = Devise.friendly_token[0,20] if user.new_record?
    end
  end

  protected

  def password_required?
    new_record? || password.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to request.referer || root_path, alert: exception.message
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :set_article, only: %i[show edit update destroy]

  authorize_resource

  def index
    @q = Article.ransack(params[:q])
    @pagy, @articles = pagy(@q.result.order(created_at: :desc), items: 4)
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params.merge(user: current_user))

    if @article.save
      redirect_to @article, notice: "Article was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: "Article was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy

    redirect_to articles_url, notice: "Article was successfully destroyed."
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    render template: "pages/#{params[:page]}"
  rescue ActionView::MissingTemplate
    render "errors/not_found", status: 404
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    omniauth_callback('Google', 'google_data')
  end

  def github
    omniauth_callback('GitHub', 'github_data')
  end

  def facebook
    omniauth_callback('Facebook', 'facebook_data')
  end

  private

  def omniauth_callback(kind, session_key)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: kind
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{session_key}"] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @q = User.ransack(params[:q])
    @pagy, @users = pagy(@q.result.order(created_at: :desc), items: 5)
  end

  def show
    @user = User.find(params[:id])

    render layout: false
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to current_user, notice: "Account was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    current_user.destroy

    redirect_to root_path, notice: "Account was successfully deleted."
  end

  private

  def user_params
    params.require(:user).permit(:avatar, :name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
  include Heroicon::Engine.helpers

  def page_title
    "Rails + Ralix + Tailwind | #{controller_name.humanize}"
  end

  def body_class
    "#{controller_name}-#{action_name}"
  end

  def nav_link_class(section, extra = nil)
    if section == controller_name
      "bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium #{extra}"
    else
      "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium #{extra}"
    end
  end

  def time_ago(time_object)
    "#{time_ago_in_words(time_object)} ago"
  end

  def format_time(time_object)
    l(time_object, format: :long)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def author_and_date(article)
    "by #{article.user.name} | #{format_time(article.created_at.to_date)}"
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar(user, size = 40)
    image_tag avatar_url(user, size),
      size: size,
      class: "rounded-full"
  end

  def avatar_url(user, size)
    if user.avatar.attached?
      url_for(user.avatar)
    else
      gravatar_url(user.email, size)
    end
  end

  def gravatar_url(email, size)
    gravatar_id = Digest::MD5.hexdigest(email).downcase
    gravatar_options = {
      s: size,
      d: "retro"
    }

    "https://www.gravatar.com/avatar/#{gravatar_id}?#{gravatar_options.to_param}"
  end
end

app/views/application/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="my-4 p-4 bg-red-600 text-white rounded">
    <b class="text-xl"><%= pluralize(object.errors.count, "error") %> found:</b>

    <ul>
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/application/_flash_messages.html.erb
<% flash.each do |key, msg| %>
  <div class="flex items-center justify-between px-8 py-4 bg-amber-100">
    <%= msg %>
    <button onclick="closeFlashAlert()"><%= heroicon "x-mark" %></button>
  </div>
<% end %>

app/views/application/_footer.html.erb
<footer class="mx-auto mt-16 w-full max-w-container px-4 sm:px-6 lg:px-8">
  <div class="border-t border-slate-900/5 py-5">
    <p class="mt-4 text-center text-sm leading-6 text-slate-500">© <%= Time.now.year %> Ralix Core Team. All rights reserved.</p>
    <div class="mt-4 flex items-center justify-center space-x-4 text-sm font-semibold leading-6">
      <%= link_to "About us", page_path(:about) %>
      <div class="h-4 w-px bg-slate-500/20"></div>
      <%= link_to "Terms", page_path(:terms) %>
      <div class="h-4 w-px bg-slate-500/20"></div>
      <%= link_to "Privacy policy", page_path(:privacy_policy) %>
    </div>
  </div>
</footer>

app/views/application/_header.html.erb
<nav class="bg-gray-800">
  <div class="mx-auto px-6 md:px-12">
    <div class="flex h-16 items-center justify-between">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <a href="<%= root_path %>" class="text-white text-2xl">Starter Kit</h2>
        </div>
        <div class="hidden sm:block">
          <div class="ml-8 flex items-baseline space-x-4">
            <a href="<%= root_path %>" class="<%= nav_link_class("home") %>">Home</a>
            <a href="<%= articles_path %>" class="<%= nav_link_class("articles") %>">Articles</a>
            <a href="<%= users_path %>" class="<%= nav_link_class("users") %>">Users</a>
          </div>
        </div>
      </div>
      <div class="hidden sm:block">
        <div class="ml-4 flex items-center md:ml-6">
          <div class="relative ml-3">
            <% if user_signed_in? %>
              <a href="<%= edit_user_path %>" class="flex max-w-xs items-center rounded-full bg-gray-800 text-sm">
                <%= avatar(current_user) %>
              </a>
            <% else %>
              <%= link_to "Sign in", new_user_session_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="sm:hidden">
        <button class="<%= nav_link_class(nil) %>" onclick="toggleMenu()">
          <%= heroicon "bars-3" %>
        </button>
      </div>
    </div>
  </div>

  <div class="sm:hidden hidden mobile-menu">
    <div class="space-y-2 px-2 pb-3 sm:px-3">
      <a href="<%= root_path %>" class="<%= nav_link_class("home", "block") %>">Home</a>
      <a href="<%= articles_path %>" class="<%= nav_link_class("articles", "block") %>">Articles</a>
      <a href="<%= users_path %>" class="<%= nav_link_class("users", "block") %>">Users</a>
      <% unless user_signed_in? %>
        <a href="<%= new_user_session_path %>" class="<%= nav_link_class(nil, "block") %>">Sign in</a>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <div class="border-t border-gray-700 py-4">
        <a href="<%= edit_user_path %>">
          <div class="flex items-center px-5">
            <div class="flex-shrink-0">
              <%= avatar(current_user) %>
            </div>
            <div class="ml-3">
              <div class="text-base font-medium leading-none text-white"><%= current_user.name %></div>
              <div class="text-sm font-medium leading-none text-gray-400"><%= current_user.email %></div>
            </div>
          </div>
        </a>
      </div>
    <% end %>
  </div>
</nav>

app/views/application/_remote_modal.html.erb
<div class="modal" id="remote-modal" aria-hidden="true">
  <div class="modal-overlay" tabindex="-1" data-micromodal-close>
    <div class="modal-container" role="dialog">
      <header class="flex items-center justify-between">
        <h1 class="modal-title"></h1>
        <button class="outline-none" data-micromodal-close>
          <%= heroicon "x-mark", options: { class: "w-8 h-8" } %>
        </button>
      </header>
      <main class="my-2">
        <p>Loading ...</p>
      </main>
    </div>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <%= render "application/error_messages", object: article %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %>
    <%= form.text_area :body, rows: 10 %>
  </div>

  <div class="mt-4">
    <%= form.submit nil, class: 'btn' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<div class="mt-8">
  <p>Be careful! This action is irreversible.</p>
  <%= button_to "Destroy", @article, method: :delete, class: "btn btn-danger" %>
</div>

app/views/articles/index.html.erb
<div class="flex items-center justify-between">
  <h1>Articles</h1>
  <%= link_to new_article_path, class: 'btn' do %>
    <%= heroicon "plus" %>
    New article
  <% end %>
</div>

<%= search_form_for @q, data: { turbo_frame: "search" } do |f| %>
  <div class="relative">
    <div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
      <%= heroicon "magnifying-glass" %>
    </div>
    <%= f.text_field :title_or_body_cont, class: "search-input p-3 pl-10 text-sm", onkeyup: "search()", placeholder: "Search ..." %>
  </div>
<% end %>

<%= turbo_frame_tag "search", target: "_top" do %>
  <div class="mt-8 grid sm:grid-cols-2 gap-8">
    <% @articles.each do |article| %>
      <article class="card">
        <h3 class="card-title">
          <%= link_to article.title, article %>
        </h3>
        <p class="card-subtitle">
          <%= author_and_date(article) %>
        </p>
        <div class="card-body">
          <%= truncate article.body, length: 160 %>
        </div>
        <div class="card-actions">
          <%= link_to 'Read more', article, class: 'btn btn-outline' %>
        </div>
      </article>
    <% end %>
  </div>

  <div class="text-center mt-10">
    <%== pagy_nav(@pagy) %>
  </div>
<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<div class="card my-4">
  <h1 class="card-title"><%= @article.title %></h1>

  <p class="card-subtitle">
    <%= author_and_date(@article) %>
  </p>

  <div class="card-body">
    <%= simple_format @article.body %>
  </div>

  <div class="card-actions">
    <%= link_to "Edit", edit_article_path(@article), class: 'btn' %>
  </div>
</div>

app/views/home/index.html.erb
<div class="text-center my-24">
  <h1 class="tracking-tight text-gray-900 sm:text-5xl md:text-6xl">
    <span>Starter Kit</span><br>
    <span class="text-indigo-600">Rails + Ralix + Tailwind</span>
  </h1>

  <p class="mt-5 mb-10 text-gray-500 sm:text-lg md:text-xl">Starter Kit to build Rails applications fast, with Ralix, Tailwind and more!</p>

  <a href="https://github.com/ralixjs/rails-ralix-tailwind" class="btn">Get started</a>
  <a href="<%= articles_path %>" class="btn btn-outline ml-4">Explore app</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" href="/favicon.ico">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="<%= body_class %>">
    <%= render "application/header" %>
    <%= render "application/flash_messages" %>
    <main>
      <div class="mx-auto p-6 md:px-12">
        <%= yield %>
      </div>
    </main>
    <%= render "application/footer" %>
    <%= render "application/remote_modal" %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>

<p><%= Faker::Lorem.paragraphs(number: 5).join.html_safe %></p>

<h2>Mission</h2>

<p><%= Faker::Lorem.paragraphs(number: 5).join.html_safe %></p>
<p><%= Faker::Lorem.paragraphs(number: 5).join.html_safe %></p>

<h2>Values</h2>

<p><%= Faker::Lorem.paragraphs(number: 5).join.html_safe %></p>
<p><%= Faker::Lorem.paragraphs(number: 5).join.html_safe %></p>

<h2>Team</h2>

<p><%= Faker::Lorem.paragraphs(number: 5).join.html_safe %></p>
<p><%= Faker::Lorem.paragraphs(number: 5).join.html_safe %></p>

app/views/pages/privacy_policy.html.erb
<h1>Privacy policy</h1>

<p><%= Faker::Lorem.paragraphs(number: 5).join.html_safe %></p>
<p><%= Faker::Lorem.paragraphs(number: 5).join.html_safe %></p>
<p><%= Faker::Lorem.paragraphs(number: 5).join.html_safe %></p>

app/views/pages/terms.html.erb
<h1>Terms</h1>

<p><%= Faker::Lorem.paragraphs(number: 5).join.html_safe %></p>
<p><%= Faker::Lorem.paragraphs(number: 5).join.html_safe %></p>
<p><%= Faker::Lorem.paragraphs(number: 5).join.html_safe %></p>

app/views/users/edit.html.erb
<h1>My account</h1>

<%= form_with(model: current_user) do |form| %>
  <%= render "application/error_messages", object: current_user %>

  <div class="mb-4">
    <%= avatar(current_user, 200) %>
  </div>

  <div>
    <%= form.label :avatar %>
    <%= form.file_field :avatar, accept: "image/*" %>
  </div>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="form-actions">
    <%= form.submit nil, class: 'btn' %>
  </div>
<% end %>

<div class="mt-8">
  <p>Sign out from my account.</p>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-outline" %>
</div>

<div class="mt-8">
  <p>Be careful! This action is irreversible.</p>
  <%= button_to "Delete my account", user_path(current_user), method: :delete, class: "btn btn-danger" %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<div class="table-responsive mt-8">
  <table>
    <thead>
      <tr>
        <th></th>
        <th><%= sort_link(@q, :name) %></th>
        <th><%= sort_link(@q, :email) %></th>
        <th><%= sort_link(@q, :created_at) %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td class="text-center">
            <%= avatar(user, 60) %>
          </td>
          <td>
            <%= user.name %>
          </td>
          <td>
            <%= mail_to user.email, 'data-tippy-content': 'Click to send an email' %>
          </td>
          <td>
            <span data-tippy-content="<%= format_time(user.created_at) %>"><%= time_ago user.created_at %></span>
          </td>
          <td>
            <a data-modal-url="<%= "/users/#{user.id}" %>" data-modal-title="User details" class="btn btn-outline">Details</a>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="text-center mt-10">
  <%== pagy_nav(@pagy) %>
</div>

app/views/users/show.html.erb
<div class="my-4 text-center">
  <%= avatar(@user, 200) %>
  <p class="text-2xl"><%= @user.name %></p>
  <p><%= mail_to @user.email %></p>
</div>

<div class="my-4">
  <p>
    <b>Created at</b>
    <%= time_ago @user.created_at %>
    <span class="text-xs text-slate-500"><%= format_time @user.created_at %></span>
  </p>
  <p>
    <b>Updated at</b>
    <%= time_ago @user.updated_at %>
    <span class="text-xs text-slate-500"><%= format_time @user.updated_at %></span>
  </p>
  <p><b>Total Articles</b> <%= @user.articles.size %></p>
</div>